---
- name: This describes how to start nginx service.
  hosts: all
  gather_facts: yes
  become: true
  become_method: sudo

  tasks:
  - name: stopping nginx service
    service:
      name: nginx
      state: stopped
...
